### ISSUE TITLE
Okta settings?

### ISSUE THREAD

**Issue by winkler1** [ThoughtWorksInc/okta-samples#5]
Hi-
 Could you please show the corresponding server-side Okta settings? There are so many it's confusing to figure them out!

This stuff--
![image](https://cloud.githubusercontent.com/assets/883896/6921036/278ef6f0-d790-11e4-81e9-52e2fa0dffc0.png)

**Comment by uday-rayala** [comment]
I have added it here. https://github.com/ThoughtWorksInc/okta-samples/blob/master/okta-server-setup.png.

**Comment by winkler1** [comment]
Awesome, thanks!
